import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const supportedLocales = [Locale('fr'), Locale('en')];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _values = {
    'fr': {
      'appTitle': 'GarageFinder',
      'home': 'Accueil',
      'garages': 'Garages',
      'favorites': 'Favoris',
      'emptyFavorites': 'Aucun garage enregistré pour le moment',
      'add': 'Ajouter',
      'settings': 'Réglages',
      'findGarage': 'Trouver un garage',
      'findGarageSubtitle': 'Garages vérifiés, rapides et proches de vous',
      'searchHint': 'Nom, ville, mécanique, dépannage...',
      'recommended': 'Ateliers recommandés',
      'emergency': 'Dépannage urgent',
      'openNow': 'Ouvert maintenant',
      'allCities': 'Toutes les villes',
      'allSpecialties': 'Toutes les spécialités',
      'near': 'Proche',
      'rating': 'Note',
      'fast': 'Rapide',
      'noGarage': 'Aucun garage trouvé',
      'details': 'Détails',
      'call': 'Appeler',
      'contactWhatsApp': 'Contacter sur WhatsApp',
      'requestWorkflowInfo':
          'Envoie les détails pour suivre la réponse ici. Pour une urgence immédiate, appelle ou écris directement au garage.',
      'sendingRequest': 'Envoi de la demande…',
      'route': 'Itinéraire',
      'save': 'Enregistrer',
      'language': 'Langue',
      'theme': 'Thème',
      'darkMode': 'Mode sombre',
      'lightMode': 'Mode clair',
      'notFound': 'Garage introuvable',
      'backToList': 'Retour à la liste',
      'back': 'Retour',
      'launchFailed': 'Impossible d’ouvrir cette application sur cet appareil.',
      'favoriteOn': 'Retirer des favoris',
      'favoriteOff': 'Ajouter aux favoris',
      'overview': 'Aperçu',
      'information': 'Informations',
      'address': 'Adresse',
      'hours': 'Horaires',
      'phone': 'Téléphone',
      'manager': 'Chef de garage',
      'trust': 'Confiance',
      'verified': 'Garage vérifié',
      'unverified': 'Garage non vérifié',
      'source': 'Source',
      'services': 'Services',
      'location': 'Localisation',
      'status': 'Statut',
      'distance': 'Distance',
      'openStatus': 'Ouvert',
      'closedStatus': 'Fermé',
      'offlineMode': 'Connexion indisponible',
      'offlineCacheUpdated': 'Dernière mise à jour :',
      'offlineCacheUnknown':
          'Les garages affichés peuvent ne pas être à jour. Appelle avant de te déplacer.',
      'version': 'Version 1.2.0',
      'registerGarage': 'Référencer un garage',
      'formHeader': 'Inscription atelier et dépannage',
      'formIntro':
          'Renseignez les détails de votre atelier mécanique ou dépannage',
      'garageName': 'Nom du garage ou atelier',
      'fullAddress': 'Adresse complète / Quartier',
      'contactPhone': 'Téléphone de contact / Urgence',
      'managerName': 'Responsable ou chef d’atelier',
      'specialtyLabel': 'Spécialité (Auto, Moto, Électricité, Dépannage)',
      'specialtyAuto': 'Auto',
      'specialtyMoto': 'Moto / scooter',
      'specialtyUtilityVehicles': 'Véhicules utilitaires',
      'specialtyHeavyVehicles': 'Poids lourds / bus',
      'specialtyRoadside': 'Dépannage / remorquage',
      'specialtyElectrical': 'Électricité / électronique',
      'specialtyDiagnostics': 'Diagnostic',
      'specialtyTires': 'Pneumatiques',
      'specialtyBodywork': 'Carrosserie / peinture',
      'specialtyBrakes': 'Freinage / suspension',
      'specialtyEngine': 'Moteur / transmission',
      'specialtyAirConditioning': 'Climatisation',
      'specialtyMaintenance': 'Vidange / entretien',
      'specialtyBattery': 'Batterie / démarrage',
      'specialtyGlass': 'Vitrage',
      'specialtyOther': 'Autre',
      'specialtyHelper': 'Sélectionne toutes les activités de ton garage.',
      'otherSpecialtyHint': 'Précise cette autre spécialité',
      'specialtiesFilterTitle': 'Spécialités et services',
      'specialtiesSelected': 'sélectionnés',
      'applyFilters': 'Appliquer les filtres',
      'clearSpecialties': 'Tout effacer',
      'imageTitle':
          'Photo de présentation (sélectionnez une image professionnelle)',
      'saveGarage': 'Enregistrer le garage',
      'cancel': 'Annuler',
      'nameRequired': 'Nom requis',
      'nameTooShort': 'Nom trop court',
      'addressRequired': 'Adresse requise',
      'phoneRequired': 'Téléphone requis',
      'invalidPhone': 'Numéro invalide',
      'phoneVerificationTitle': 'Vérification du numéro du garage',
      'phoneVerificationHint':
          'Saisis le numéro au format international, par exemple +229XXXXXXXXXX.',
      'sendPhoneCode': 'Envoyer le code SMS',
      'resendPhoneCode': 'Renvoyer le code',
      'phoneCodeLabel': 'Code reçu par SMS',
      'verifyPhoneCode': 'Vérifier le code',
      'phoneVerified': 'Numéro du garage vérifié',
      'phoneVerificationRequired':
          'Vérifie le numéro du garage avant de l’enregistrer.',
      'phoneMustBeE164':
          'Utilise le format international, par exemple +229XXXXXXXXXX.',
      'phoneCodeSent': 'Code envoyé par SMS. Il expire dans 10 minutes.',
      'phoneCodeInvalid': 'Code incorrect. Vérifie le SMS et réessaie.',
      'phoneCodeExpired': 'Code expiré. Demande un nouveau code.',
      'phoneCodeWait': 'Patiente une minute avant de demander un autre code.',
      'phoneCodeRateLimit':
          'Limite atteinte : 3 codes maximum par heure. Réessaie plus tard.',
      'phoneSmsUnavailable':
          'Le SMS n’a pas pu être envoyé. Vérifie le numéro ou réessaie plus tard.',
      'phoneVerificationUnavailable':
          'La vérification est momentanément indisponible.',
      'automatedReviewPassed':
          'Contrôles automatiques passés. La validation finale Garage Finder reste en attente.',
      'automatedReviewNeedsReview':
          'Contrôle automatique complémentaire requis avant publication.',
      'autoChecksPassedShort': 'Contrôles automatiques passés',
      'autoNeedsReviewShort': 'À vérifier par un modérateur',
      'autoNotCheckedShort': 'Contrôle automatique non effectué',
      'phoneUsedByAnotherOwner': 'Numéro utilisé par un autre compte',
      'possibleDuplicateNearby': 'Garage similaire à proximité',
      'garagePhotoMissing': 'Photo du garage manquante',
      'onSitePresenceTitle': 'Confirmer votre présence sur place',
      'onSitePresenceHint':
          'Depuis le garage, vérifie que ta position correspond à son épingle.',
      'verifyOnSitePresence': 'Vérifier ma présence',
      'onSitePresenceVerified': 'Signal GPS de proximité reçu',
      'onSitePresenceMissing': 'Signal GPS de proximité absent',
      'onSitePresenceFailed':
          'La position doit être à moins de 150 m du garage avec une précision de 50 m maximum.',
      'onSitePresenceMocked':
          'Une position simulée ne peut pas servir à vérifier le garage.',
      'onSitePresenceRequired':
          'Une vérification sur place est nécessaire pour réussir les contrôles automatiques.',
      'autoPhotoRequired':
          'Une photo du garage est nécessaire pour réussir les contrôles automatiques.',
      'automatedReviewCaveat':
          'Ces signaux réduisent le risque de fraude sans garantir à eux seuls l’existence légale du garage.',
      'specialtyRequired': 'Choisis au moins une spécialité.',
      'garageAdded': 'Garage "{name}" ajouté avec succès !',
      'clearSearch': 'Effacer la recherche',
      'results': 'résultats',
      'result': 'résultat',
      'open': 'OUVERT',
      'closed': 'FERMÉ',
      'view': 'Voir',
      'presetService': 'Dépannage & Service',
      'presetCar': 'Mécanique auto',
      'presetMotorcycle': 'Atelier moto',
      'presetEmergency': 'Assistance SOS panne',
      'account': 'Compte',
      'signIn': 'Se connecter',
      'signUp': 'Créer un compte',
      'signOut': 'Se déconnecter',
      'createAccount': 'Créer mon compte',
      'email': 'Adresse e-mail',
      'password': 'Mot de passe',
      'displayName': 'Nom complet',
      'garageOwner': 'Je suis garagiste',
      'customer': 'Je cherche un garage',
      'chooseAccountType': 'Quel type de compte veux-tu créer ?',
      'customerRole': 'Client',
      'garageOwnerRole': 'Garagiste',
      'customerAccountTitle': 'Compte client',
      'garageAccountTitle': 'Compte garagiste',
      'garageAddress': 'Adresse complète du garage',
      'garageAddressHint':
          'Saisis l’adresse exacte puis localise-la, ou utilise le GPS en étant sur place.',
      'garageLocationRequired':
          'Indique l’adresse du garage et confirme son emplacement sur la carte avant de créer le compte.',
      'garageLocationPrivacy':
          'Cette position sera enregistrée pour préparer la fiche du garage et permettre aux clients de le trouver.',
      'openMapLocation': 'Vérifier sur Google Maps',
      'forgotPassword': 'Mot de passe oublié ?',
      'resetSent': 'E-mail de réinitialisation envoyé.',
      'checkEmail': 'Vérifie ton e-mail pour confirmer le compte.',
      'resendConfirmation': 'Renvoyer l’e-mail de confirmation',
      'confirmationResent': 'Un nouvel e-mail de confirmation a été envoyé.',
      'invalidEmail': 'Saisis une adresse e-mail valide.',
      'emailLinkExpiredTitle': 'Ce lien de confirmation a expiré',
      'emailLinkExpiredBody':
          'Le lien est expiré ou a déjà été utilisé. Reviens à la création de compte, saisis la même adresse et demande un nouvel e-mail.',
      'emailLinkFailedTitle': 'Confirmation impossible',
      'emailLinkFailedBody':
          'Le lien ne peut pas être validé. Demande un nouvel e-mail de confirmation.',
      'emailConfirmedTitle': 'Adresse e-mail confirmée',
      'emailConfirmedBody': 'Ton compte Garage Finder est prêt.',
      'continueToApp': 'Continuer vers Garage Finder',
      'authRateLimited':
          'Trop de demandes ont été envoyées. Vérifie ta boîte mail et les indésirables, puis réessaie plus tard sans renvoyer plusieurs fois le formulaire.',
      'customerAccountHelp':
          'La recherche est libre. Ce compte sert à envoyer des demandes de dépannage et à laisser un avis après une intervention.',
      'garageAccountHelp':
          'Ce compte permet d’enregistrer et gérer tes garages, puis de répondre aux demandes des clients.',
      'backendMissing': 'Backend non configuré. Mode démonstration actif.',
      'ownerDashboard': 'Espace garagiste',
      'explore': 'Explorer',
      'ownerOverview': 'Vue d’ensemble',
      'ownerInbox': 'Demandes des clients',
      'requestsToHandle': 'À traiter',
      'requestsInProgress': 'En cours',
      'requestsClosed': 'Clôturées',
      'requestFilterAll': 'Toutes',
      'requestFilterPending': 'À traiter',
      'requestFilterActive': 'En cours',
      'requestFilterClosed': 'Historique',
      'noRequestsForFilter': 'Aucune demande dans cette catégorie.',
      'clientName': 'Client',
      'garageLabel': 'Garage concerné',
      'callCustomer': 'Appeler le client',
      'messageCustomer': 'Écrire au client sur WhatsApp',
      'openCustomerLocation': 'Ouvrir la position du client sur la carte',
      'requestReceivedAt': 'Reçue le',
      'requestLoadFailed': 'Impossible de charger les demandes clients.',
      'linkUnavailable': 'Impossible d’ouvrir ce lien sur cet appareil.',
      'myGarages': 'Mes garages',
      'pendingReview': 'En attente de validation',
      'approved': 'Publié et vérifié',
      'rejected': 'Refusé',
      'noGaragesYet': 'Aucun garage enregistré pour le moment.',
      'ownerSetupTitle': 'Préparer votre présence sur Garage Finder',
      'ownerSetupProgress': 'Configuration : {done}/3 étapes terminées',
      'ownerProfileStep': 'Profil et coordonnées professionnelles renseignés',
      'ownerLocationStep': 'Adresse et position du garage vérifiées',
      'ownerListingStep': 'Fiche garage enregistrée',
      'ownerReviewStep': 'Validation de la fiche par Garage Finder',
      'ownerReviewInProgress': 'Votre fiche est en cours de vérification.',
      'addMyGarage': 'Ajouter mon garage',
      'deleteGarage': 'Supprimer ce garage ?',
      'locationPermissionDenied': 'Autorise la localisation pour continuer.',
      'locationUnavailable': 'Position introuvable. Vérifie le GPS.',
      'useMyLocation': 'Utiliser ma position',
      'manualLocation': 'Saisir les coordonnées',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'geocodeAddress': 'Localiser cette adresse',
      'googleMapsLink': 'Lien Google Maps du garage',
      'googleMapsLinkHint':
          'Colle un lien de repère avec ses coordonnées. Les liens courts peuvent ne pas être lisibles.',
      'useMapLink': 'Importer le repère Maps',
      'invalidMapLink':
          'Lien Maps non reconnu. Utilise un lien contenant un repère ou saisis les coordonnées.',
      'mapLinkLoaded': 'Position importée depuis Google Maps.',
      'requestMapLinkHint':
          'Facultatif : le lien indique le lieu de la panne et remplace le GPS.',
      'addressLookupUnavailable':
          'Le repérage automatique n’est pas disponible ici. Saisis les coordonnées GPS ou utilise ta position.',
      'locationFound': 'Position trouvée',
      'locationNotFound': 'Adresse introuvable. Saisis les coordonnées.',
      'searchRadius': 'Rayon de recherche',
      'findNearby': 'Autour de moi',
      'saveForReview': 'Soumettre pour validation',
      'photoOptional': 'Photo du garage (facultatif)',
      'changeGaragePhoto': 'Changer la photo du garage',
      'garagePhotoPreview': 'Aperçu de la photo du garage',
      'removeGaragePhoto': 'Retirer la photo du garage',
      'photoFormatInvalid': 'Format accepté : JPG, PNG ou WebP.',
      'photoTooLarge': 'La photo doit faire 5 Mo maximum.',
      'photoPickFailed': 'Impossible de sélectionner cette photo.',
      'photoUploadFailed': 'La fiche est enregistrée sans la photo.',
      'priceMin': 'Prix minimum (FCFA)',
      'priceMax': 'Prix maximum (FCFA)',
      'servicesHint': 'Services, séparés par des virgules',
      'distanceUnavailable': 'Distance disponible après recherche',
      'accountRequired': 'Connecte-toi avec un compte garagiste.',
      'budget': 'Budget de réparation',
      'invalidPriceRange': 'Le minimum doit être inférieur au maximum.',
      'responseTimeMinutes': 'Délai de réponse (minutes)',
      'city': 'Ville',
      'showPassword': 'Afficher le mot de passe',
      'hidePassword': 'Masquer le mot de passe',
      'editGarage': 'Modifier la fiche',
      'weeklyHours': 'Horaires hebdomadaires',
      'availability': 'Disponibilité actuelle',
      'availability_available': 'Disponible',
      'availability_busy': 'Occupé',
      'availability_emergency_only': 'Dépannage urgent uniquement',
      'availability_unavailable': 'Indisponible',
      'availabilityUpdated': 'Mise à jour :',
      'day_mon': 'Lun',
      'day_tue': 'Mar',
      'day_wed': 'Mer',
      'day_thu': 'Jeu',
      'day_fri': 'Ven',
      'day_sat': 'Sam',
      'day_sun': 'Dim',
      'activity': 'Activité',
      'myRequests': 'Mes demandes',
      'notifications': 'Notifications',
      'noRequests': 'Aucune demande pour le moment.',
      'noNotifications': 'Aucune notification.',
      'markRead': 'Marquer comme lue',
      'incomingRequests': 'Demandes reçues',
      'updateRequest': 'Mettre à jour la demande',
      'acceptRequest': 'Accepter',
      'declineRequest': 'Refuser',
      'enRoute': 'En route',
      'completeRequest': 'Terminer',
      'requestHelp': 'Demander un dépannage',
      'vehicle': 'Véhicule (marque et modèle)',
      'describeBreakdown': 'Décris la panne et le lieu',
      'shareLocationWithGarage': 'Partager ma position avec ce garage',
      'locationPrivacyNotice':
          'La position précise ne sera jointe qu’à cette demande.',
      'sendRequest': 'Envoyer la demande',
      'requestSent': 'Demande envoyée. Tu seras informé de la réponse.',
      'requiredField': 'Champ requis (au moins 2 caractères).',
      'writeReview': 'Donner un avis',
      'reviewComment': 'Commentaire (facultatif)',
      'sendReview': 'Envoyer l’avis',
      'reviewSaved': 'Avis enregistré. Merci !',
      'customerSignInRequired':
          'Connecte-toi avec un compte client pour continuer.',
      'customerAccountRequired':
          'Crée un compte client ou connecte-toi pour envoyer une demande et suivre son avancement.',
      'reportGarage': 'Signaler cette fiche',
      'report_phone': 'Téléphone incorrect',
      'report_address': 'Adresse incorrecte',
      'report_closed': 'Garage fermé ou introuvable',
      'report_behavior': 'Comportement inapproprié',
      'report_other': 'Autre problème',
      'reportDetails': 'Détails (facultatif)',
      'sendReport': 'Envoyer le signalement',
      'reportSent': 'Signalement transmis à la modération.',
      'moderation': 'Modération',
      'moderationAccessDenied': 'Accès réservé à l’équipe de modération.',
      'noReports': 'Aucun signalement.',
      'updateReport': 'Traiter le signalement',
      'reportReviewing': 'En cours de traitement',
      'reportResolved': 'Résolu',
      'reportDismissed': 'Écarté',
      'requestStatus_pending': 'En attente',
      'requestStatus_accepted': 'Acceptée',
      'requestStatus_en_route': 'En route',
      'requestStatus_completed': 'Terminée',
      'requestStatus_declined': 'Refusée',
      'requestStatus_cancelled': 'Annulée par le client',
      'requestStatus_expired': 'Expirée sans réponse',
      'cancelRequest': 'Annuler la demande',
      'confirmCancelRequest':
          'Cette action est définitive. Le garage ne pourra plus répondre à cette demande.',
      'keepRequest': 'Garder la demande',
      'requestCancelled': 'Demande annulée.',
      'requestNoLongerPending':
          'La demande a déjà été prise en charge et ne peut plus être annulée.',
      'etaMinutes': 'Délai estimé (minutes)',
      'invalidEta': 'Saisis un délai entre 0 et 1440 minutes.',
      'hoursNotSet': 'Horaires non renseignés',
      'reviews': 'Avis clients',
      'noReviews': 'Pas encore d’avis.',
      'ratingOnly': 'Note laissée sans commentaire.',
      'garageSaved':
          'Fiche mise à jour. Les changements importants seront revalidés.',
      'reviewAfterService':
          'Un avis est possible après une demande de dépannage terminée.',
      'garageReviewQueue': 'Fiches à valider',
      'reports': 'Signalements',
      'noPendingGarages': 'Aucune fiche à valider.',
      'moderateGarage': 'Examiner cette fiche',
      'reviewApprove': 'Approuver',
      'reviewReject': 'Refuser',
      'moderationNote': 'Motif du refus (10 caractères minimum)',
      'moderationNoteRequired': 'Indique un motif d’au moins 10 caractères.',
      'moderationNoteFromTeam': 'Motif de la modération',
      'reviewStatus_pending': 'En attente',
      'reviewStatus_approved': 'Approuvée',
      'reviewStatus_rejected': 'Refusée',
      'reportStatus_open': 'Nouveau',
      'reportStatus_reviewing': 'En cours de traitement',
      'reportStatus_resolved': 'Résolu',
      'reportStatus_dismissed': 'Écarté',
    },
    'en': {
      'appTitle': 'GarageFinder',
      'home': 'Home',
      'garages': 'Garages',
      'favorites': 'Favorites',
      'emptyFavorites': 'No saved garages yet',
      'add': 'Add',
      'settings': 'Settings',
      'findGarage': 'Find a garage',
      'findGarageSubtitle': 'Verified, fast garages near you',
      'searchHint': 'Name, city, mechanic, breakdown...',
      'recommended': 'Recommended workshops',
      'emergency': 'Emergency repair',
      'openNow': 'Open now',
      'allCities': 'All cities',
      'allSpecialties': 'All specialties',
      'near': 'Near',
      'rating': 'Rating',
      'fast': 'Fast',
      'noGarage': 'No garage found',
      'details': 'Details',
      'call': 'Call',
      'contactWhatsApp': 'Contact on WhatsApp',
      'requestWorkflowInfo':
          'Send the details to track the reply here. For immediate help, call or message the garage directly.',
      'sendingRequest': 'Sending request…',
      'route': 'Route',
      'save': 'Save',
      'language': 'Language',
      'theme': 'Theme',
      'darkMode': 'Dark mode',
      'lightMode': 'Light mode',
      'notFound': 'Garage not found',
      'backToList': 'Back to garages',
      'back': 'Back',
      'launchFailed': 'Could not open an app for this action.',
      'favoriteOn': 'Remove from favorites',
      'favoriteOff': 'Add to favorites',
      'overview': 'Overview',
      'information': 'Information',
      'address': 'Address',
      'hours': 'Opening hours',
      'phone': 'Phone',
      'manager': 'Garage manager',
      'trust': 'Trust',
      'verified': 'Verified garage',
      'unverified': 'Unverified garage',
      'source': 'Source',
      'services': 'Services',
      'location': 'Location',
      'status': 'Status',
      'distance': 'Distance',
      'openStatus': 'Open',
      'closedStatus': 'Closed',
      'offlineMode': 'Connection unavailable',
      'offlineCacheUpdated': 'Last updated:',
      'offlineCacheUnknown':
          'These garage listings may be out of date. Call before travelling.',
      'version': 'Version 1.2.0',
      'registerGarage': 'Register a garage',
      'formHeader': 'Workshop and roadside assistance registration',
      'formIntro': 'Enter your workshop or roadside assistance details',
      'garageName': 'Garage or workshop name',
      'fullAddress': 'Full address / neighborhood',
      'contactPhone': 'Contact / emergency phone',
      'managerName': 'Workshop manager',
      'specialtyLabel': 'Specialty (cars, motorcycles, electrical, roadside)',
      'specialtyAuto': 'Cars',
      'specialtyMoto': 'Motorcycles / scooters',
      'specialtyUtilityVehicles': 'Utility vehicles',
      'specialtyHeavyVehicles': 'Heavy vehicles / buses',
      'specialtyRoadside': 'Roadside assistance / towing',
      'specialtyElectrical': 'Electrical / electronics',
      'specialtyDiagnostics': 'Diagnostics',
      'specialtyTires': 'Tires',
      'specialtyBodywork': 'Bodywork / paint',
      'specialtyBrakes': 'Brakes / suspension',
      'specialtyEngine': 'Engine / transmission',
      'specialtyAirConditioning': 'Air conditioning',
      'specialtyMaintenance': 'Oil change / maintenance',
      'specialtyBattery': 'Battery / starting',
      'specialtyGlass': 'Glass',
      'specialtyOther': 'Other',
      'specialtyHelper': 'Select every service your garage offers.',
      'otherSpecialtyHint': 'Describe this other specialty',
      'specialtiesFilterTitle': 'Specialties and services',
      'specialtiesSelected': 'selected',
      'applyFilters': 'Apply filters',
      'clearSpecialties': 'Clear all',
      'imageTitle': 'Cover photo (choose a professional image)',
      'saveGarage': 'Save garage',
      'cancel': 'Cancel',
      'nameRequired': 'Name is required',
      'nameTooShort': 'Name is too short',
      'addressRequired': 'Address is required',
      'phoneRequired': 'Phone is required',
      'invalidPhone': 'Invalid phone number',
      'phoneVerificationTitle': 'Verify the garage phone number',
      'phoneVerificationHint':
          'Enter the number in international format, for example +229XXXXXXXXXX.',
      'sendPhoneCode': 'Send SMS code',
      'resendPhoneCode': 'Send a new code',
      'phoneCodeLabel': 'Code received by SMS',
      'verifyPhoneCode': 'Verify code',
      'phoneVerified': 'Garage phone verified',
      'phoneVerificationRequired':
          'Verify the garage phone number before saving it.',
      'phoneMustBeE164':
          'Use international format, for example +229XXXXXXXXXX.',
      'phoneCodeSent': 'SMS code sent. It expires in 10 minutes.',
      'phoneCodeInvalid': 'Incorrect code. Check the SMS and try again.',
      'phoneCodeExpired': 'Code expired. Request a new one.',
      'phoneCodeWait': 'Wait one minute before requesting another code.',
      'phoneCodeRateLimit':
          'Limit reached: up to 3 codes per hour. Try again later.',
      'phoneSmsUnavailable':
          'The SMS could not be sent. Check the number or try again later.',
      'phoneVerificationUnavailable':
          'Verification is temporarily unavailable.',
      'automatedReviewPassed':
          'Automated checks passed. Final Garage Finder approval is still pending.',
      'automatedReviewNeedsReview':
          'Additional automated review is required before publication.',
      'autoChecksPassedShort': 'Automated checks passed',
      'autoNeedsReviewShort': 'Moderator review required',
      'autoNotCheckedShort': 'Automated checks not completed',
      'phoneUsedByAnotherOwner': 'Phone used by another account',
      'possibleDuplicateNearby': 'Similar nearby garage',
      'garagePhotoMissing': 'Garage photo missing',
      'onSitePresenceTitle': 'Confirm on-site presence',
      'onSitePresenceHint':
          'While at the garage, check that your position matches its map pin.',
      'verifyOnSitePresence': 'Verify my presence',
      'onSitePresenceVerified': 'GPS proximity signal received',
      'onSitePresenceMissing': 'GPS proximity signal missing',
      'onSitePresenceFailed':
          'Location must be within 150 m of the garage with accuracy of 50 m or better.',
      'onSitePresenceMocked': 'A simulated location cannot verify a garage.',
      'onSitePresenceRequired':
          'On-site verification is required to pass automated checks.',
      'autoPhotoRequired':
          'A garage photo is required to pass automated checks.',
      'automatedReviewCaveat':
          'These signals reduce fraud risk but do not, by themselves, prove the garage legally exists.',
      'specialtyRequired': 'Select at least one specialty.',
      'garageAdded': 'Garage "{name}" added successfully!',
      'clearSearch': 'Clear search',
      'results': 'results',
      'result': 'result',
      'open': 'OPEN',
      'closed': 'CLOSED',
      'view': 'View',
      'presetService': 'Roadside assistance',
      'presetCar': 'Car mechanics',
      'presetMotorcycle': 'Motorcycle workshop',
      'presetEmergency': 'Emergency assistance',
      'account': 'Account',
      'signIn': 'Sign in',
      'signUp': 'Create account',
      'signOut': 'Sign out',
      'createAccount': 'Create my account',
      'email': 'Email address',
      'password': 'Password',
      'displayName': 'Full name',
      'garageOwner': 'I am a garage owner',
      'customer': 'I am looking for a garage',
      'chooseAccountType': 'Which type of account do you need?',
      'customerRole': 'Customer',
      'garageOwnerRole': 'Garage owner',
      'customerAccountTitle': 'Customer account',
      'garageAccountTitle': 'Garage owner account',
      'garageAddress': 'Full garage address',
      'garageAddressHint':
          'Enter the exact address and locate it, or use GPS while at the garage.',
      'garageLocationRequired':
          'Enter the garage address and confirm its map location before creating the account.',
      'garageLocationPrivacy':
          'This location will be saved to prepare the garage listing and help customers find it.',
      'openMapLocation': 'Check location on Google Maps',
      'forgotPassword': 'Forgot password?',
      'resetSent': 'Password reset email sent.',
      'checkEmail': 'Check your email to confirm your account.',
      'resendConfirmation': 'Resend confirmation email',
      'confirmationResent': 'A new confirmation email has been sent.',
      'invalidEmail': 'Enter a valid email address.',
      'emailLinkExpiredTitle': 'This confirmation link has expired',
      'emailLinkExpiredBody':
          'The link expired or was already used. Return to account creation, enter the same address, and request a new email.',
      'emailLinkFailedTitle': 'Could not confirm your email',
      'emailLinkFailedBody':
          'This link could not be verified. Request a new confirmation email.',
      'emailConfirmedTitle': 'Email address confirmed',
      'emailConfirmedBody': 'Your Garage Finder account is ready.',
      'continueToApp': 'Continue to Garage Finder',
      'authRateLimited':
          'Too many requests have been sent. Check your inbox and spam folder, then try again later without resubmitting repeatedly.',
      'customerAccountHelp':
          'Search is open to everyone. Use a customer account to request roadside help and review a garage after service.',
      'garageAccountHelp':
          'Use a garage account to register and manage your garages and respond to customer requests.',
      'backendMissing': 'Backend not configured. Demo mode is active.',
      'ownerDashboard': 'Garage owner space',
      'explore': 'Explore',
      'ownerOverview': 'Overview',
      'ownerInbox': 'Customer requests',
      'requestsToHandle': 'Needs action',
      'requestsInProgress': 'In progress',
      'requestsClosed': 'Closed',
      'requestFilterAll': 'All',
      'requestFilterPending': 'Needs action',
      'requestFilterActive': 'In progress',
      'requestFilterClosed': 'History',
      'noRequestsForFilter': 'No requests in this category.',
      'clientName': 'Customer',
      'garageLabel': 'Garage',
      'callCustomer': 'Call customer',
      'messageCustomer': 'Message customer on WhatsApp',
      'openCustomerLocation': 'Open customer location on map',
      'requestReceivedAt': 'Received',
      'requestLoadFailed': 'Could not load customer requests.',
      'linkUnavailable': 'Could not open this link on this device.',
      'myGarages': 'My garages',
      'pendingReview': 'Pending review',
      'approved': 'Published and verified',
      'rejected': 'Rejected',
      'noGaragesYet': 'No garages registered yet.',
      'ownerSetupTitle': 'Set up your Garage Finder presence',
      'ownerSetupProgress': 'Setup: {done}/3 steps complete',
      'ownerProfileStep': 'Professional profile and contact details added',
      'ownerLocationStep': 'Garage address and map location confirmed',
      'ownerListingStep': 'Garage listing submitted',
      'ownerReviewStep': 'Garage Finder listing review',
      'ownerReviewInProgress': 'Your listing is being reviewed.',
      'addMyGarage': 'Add my garage',
      'deleteGarage': 'Delete this garage?',
      'locationPermissionDenied': 'Allow location access to continue.',
      'locationUnavailable': 'Location unavailable. Check GPS settings.',
      'useMyLocation': 'Use my location',
      'manualLocation': 'Enter coordinates',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'geocodeAddress': 'Find this address',
      'googleMapsLink': 'Google Maps link for the garage',
      'googleMapsLinkHint':
          'Paste a pin link containing coordinates. Short links may not expose them.',
      'useMapLink': 'Import Maps location',
      'invalidMapLink':
          'Could not read coordinates from this Maps link. Use a pin link or enter coordinates.',
      'mapLinkLoaded': 'Location imported from Google Maps.',
      'requestMapLinkHint':
          'Optional: this pin marks the breakdown location and overrides GPS.',
      'addressLookupUnavailable':
          'Automatic address lookup is unavailable here. Enter GPS coordinates or use your current location.',
      'locationFound': 'Location found',
      'locationNotFound': 'Address not found. Enter coordinates.',
      'searchRadius': 'Search radius',
      'findNearby': 'Near me',
      'saveForReview': 'Submit for review',
      'photoOptional': 'Garage photo (optional)',
      'changeGaragePhoto': 'Change garage photo',
      'garagePhotoPreview': 'Garage photo preview',
      'removeGaragePhoto': 'Remove garage photo',
      'photoFormatInvalid': 'Accepted formats: JPG, PNG, or WebP.',
      'photoTooLarge': 'The photo must be no larger than 5 MB.',
      'photoPickFailed': 'Could not select this photo.',
      'photoUploadFailed': 'The garage listing was saved without its photo.',
      'priceMin': 'Minimum price (CFA)',
      'priceMax': 'Maximum price (CFA)',
      'servicesHint': 'Services, comma separated',
      'distanceUnavailable': 'Distance available after searching',
      'accountRequired': 'Sign in with a garage owner account.',
      'budget': 'Repair budget',
      'invalidPriceRange': 'Minimum must not exceed maximum.',
      'responseTimeMinutes': 'Response time (minutes)',
      'city': 'City',
      'showPassword': 'Show password',
      'hidePassword': 'Hide password',
      'editGarage': 'Edit garage',
      'weeklyHours': 'Weekly hours',
      'availability': 'Current availability',
      'availability_available': 'Available',
      'availability_busy': 'Busy',
      'availability_emergency_only': 'Emergency only',
      'availability_unavailable': 'Unavailable',
      'availabilityUpdated': 'Updated:',
      'day_mon': 'Mon',
      'day_tue': 'Tue',
      'day_wed': 'Wed',
      'day_thu': 'Thu',
      'day_fri': 'Fri',
      'day_sat': 'Sat',
      'day_sun': 'Sun',
      'activity': 'Activity',
      'myRequests': 'My requests',
      'notifications': 'Notifications',
      'noRequests': 'No requests yet.',
      'noNotifications': 'No notifications.',
      'markRead': 'Mark as read',
      'incomingRequests': 'Incoming requests',
      'updateRequest': 'Update request',
      'acceptRequest': 'Accept',
      'declineRequest': 'Decline',
      'enRoute': 'On the way',
      'completeRequest': 'Complete',
      'requestHelp': 'Request roadside help',
      'vehicle': 'Vehicle (make and model)',
      'describeBreakdown': 'Describe the issue and location',
      'shareLocationWithGarage': 'Share my location with this garage',
      'locationPrivacyNotice':
          'Precise location is attached only to this request.',
      'sendRequest': 'Send request',
      'requestSent': 'Request sent. You will be notified of the response.',
      'requiredField': 'Required (at least 2 characters).',
      'writeReview': 'Write a review',
      'reviewComment': 'Comment (optional)',
      'sendReview': 'Submit review',
      'reviewSaved': 'Review saved. Thank you!',
      'customerSignInRequired': 'Sign in with a customer account to continue.',
      'customerAccountRequired':
          'Create a customer account or sign in to send a request and track its progress.',
      'reportGarage': 'Report this listing',
      'report_phone': 'Incorrect phone number',
      'report_address': 'Incorrect address',
      'report_closed': 'Garage is closed or cannot be found',
      'report_behavior': 'Inappropriate behavior',
      'report_other': 'Other issue',
      'reportDetails': 'Details (optional)',
      'sendReport': 'Send report',
      'reportSent': 'Report sent to moderation.',
      'moderation': 'Moderation',
      'moderationAccessDenied': 'Access is restricted to moderators.',
      'noReports': 'No reports.',
      'updateReport': 'Process report',
      'reportReviewing': 'Under review',
      'reportResolved': 'Resolved',
      'reportDismissed': 'Dismissed',
      'requestStatus_pending': 'Pending',
      'requestStatus_accepted': 'Accepted',
      'requestStatus_en_route': 'On the way',
      'requestStatus_completed': 'Completed',
      'requestStatus_declined': 'Declined',
      'requestStatus_cancelled': 'Cancelled by you',
      'requestStatus_expired': 'Expired without a response',
      'cancelRequest': 'Cancel request',
      'confirmCancelRequest':
          'This action is permanent. The garage will no longer be able to respond.',
      'keepRequest': 'Keep request',
      'requestCancelled': 'Request cancelled.',
      'requestNoLongerPending':
          'The garage has already responded, so this request can no longer be cancelled.',
      'etaMinutes': 'Estimated time (minutes)',
      'invalidEta': 'Enter a time between 0 and 1440 minutes.',
      'hoursNotSet': 'Hours not provided',
      'reviews': 'Customer reviews',
      'noReviews': 'No reviews yet.',
      'ratingOnly': 'Rating without a comment.',
      'garageSaved':
          'Garage updated. Important changes will be reviewed again.',
      'reviewAfterService': 'You can review after a completed service request.',
      'garageReviewQueue': 'Garage approvals',
      'reports': 'Reports',
      'noPendingGarages': 'No garages to review.',
      'moderateGarage': 'Review this garage',
      'reviewApprove': 'Approve',
      'reviewReject': 'Reject',
      'moderationNote': 'Reason for rejection (10 characters minimum)',
      'moderationNoteRequired': 'Enter a reason of at least 10 characters.',
      'moderationNoteFromTeam': 'Moderator feedback',
      'reviewStatus_pending': 'Pending',
      'reviewStatus_approved': 'Approved',
      'reviewStatus_rejected': 'Rejected',
      'reportStatus_open': 'New',
      'reportStatus_reviewing': 'Under review',
      'reportStatus_resolved': 'Resolved',
      'reportStatus_dismissed': 'Dismissed',
    },
  };

  String t(String key) =>
      _values[locale.languageCode]?[key] ?? _values['fr']![key] ?? key;

  String text(String key, [Map<String, String> values = const {}]) {
    var value = t(key);
    for (final entry in values.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (item) => item.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
